import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import ConvexClerkProvider  from "../../Provider/ConvexClerkProvider";
import { Toaster } from "@/components/ui/toaster"
import AudioProvider from "../../Provider/AudioProvider";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConvexClerkProvider>    
        <AudioProvider>
      <body
        className={`${manrope.className}`}
      >
        <Toaster />
        {children}
      </body>
      </AudioProvider>
      </ConvexClerkProvider>
    </html>
  );
}
